name: GitHub Actions Create Image
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  create_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Create and publish image
        run: |
          image=${{ github.repository}}:${{ github.ref }}
          docker build . -t ghcr.io/$image
          echo ${{ secrets.PAT_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
          docker push ghcr.io/$image
