name: GitHub Actions Create Image
on: push
# on:
#   push:
#     tags:
#       - "v*.*.*"
jobs:
  create_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          image=${{ github.repository}}:${{ github.sha }}
          docker build . -t ghcr.io/$image
          echo $PAT_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
          docker push ghcr.io/$image
